### ISSUE TITLE
Add license(s)

### ISSUE THREAD

**Issue by mogambro** [tomaspecl/gravishot#3]
Hey there!

Searching for bevy_quinnet users I stumbled over this crate.

I find the rollback code very interesting and would like to kindly request a license for the project, so I know what kind of inspiration I can take.

Ideally it would be Apache/MIT but of course that's totally up to you.

In any case, thanks for your work and sharing it publicly!

**Comment by tomaspecl** [comment]
Yea the license... I should have put one in in the begining. I am going to use GPLv3 I think. However I was thinking that I would take my rollback code and clean it and move it into a separate crate eventualy so that it could be reused by someone else easily. Are you planning to use my rollback code in a library? Maybe we can make it together.

**Comment by tomaspecl** [comment]
So I put in the license. Its GPL, but if you really want Apache/MIT, I could use that when I separate the rollback code into a different crate with more general API or something like that. I am not entirely sure how I am going to do it, as I have never made any library so far but I still want to make it usable and nice.

**Comment by tomaspecl** [comment]
And also what do you find so interesting about my rollback code? I just knew some very basic concepts about rollback (like what it is and what its supposed to fix) and tried to hack it together and it kindof works. Do you think its good or is it wierd/non standard?

**Comment by mogambro** [comment]
As I've never written rollback code and just know the basics from gafferongames I found it interesting to have a peek at it.

Thanks for adding a license!
